version: 0.2

phases:
  pre_build:
    commands:
      - echo Entered prebuild phase
  build:
    commands:
      - echo Build started
      - mvn -DskipTest clean package
      - echo Doing docker build?

  post_build:
    commands:
      - echo  Build completed
artifacts:
  files:
    - target/teamservice-0.0.1-SNAPSHOT.jar
  discard-paths: yes