version: 0.2

phases:
  pre_build:
    commands:
      - echo Entered prebuild phase
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - mvn -DskipTests clean package  
      - docker-compose build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/playerservice-0.0.1-SNAPSHOT.jar
  discard-paths: yes