version: "3.1"
services:
    app:
        image: 276408663694.dkr.ecr.us-east-2.amazonaws.com/dockeroneapp
        restart: always
        build: .
        ports:
            - "8081:8081"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/teamservice
    db:
        image: 276408663694.dkr.ecr.us-east-2.amazonaws.com/dockeronedb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test1234
            MYSQL_DATABASE: teamservice
        security_opt:
            - seccomp:unconfined
        ports:
              - "3306"
        #volumes:
        #        - my-datavolume:/var/lib/mysql
#volumes:
#   my-datavolume:/var/lib/mysql