version: "3.1"
services:
    app:
        restart: always
        build: .
        ports:
            - "8081:8081"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/teamservice
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test1234
            MYSQL_DATABASE: teamservice
        security_opt:
            - seccomp:unconfined
        ports:
              - "3306"
        volumes:
                - my-datavolume:/var/lib/mysql
volumes:
    my-datavolume: